image_xscale = 0.17;
image_yscale = 0.17;
image_speed = 0;
siner = 0;
audio_stop_all();
Whiter = 0;
MoveOn = false;
Sel = 0;
Timer = 0;
x = global.SoulX;
y = global.SoulY;
global.coward = true;
obj_BattleEffects.CMAB = 0.1;
WordStage = 0;
alarm[0] = 120;
